use_load_balancer: false
credentials_db:
  image: localhost:5000/dotcv/credentials-db
  tag: testing
  storage_class_name: hostpath
  db_name: cas
  username: root
  password_secret:
    name: cas
    key: sql-root-password
  port:
    mysql: 3306
cas:
  image: localhost:5000/dotcv/sso-webapp
  tag: testing
  hostname: 192.168.64.35
  port:
    http: 32701
    https: 32702
message_validator:
  image: localhost:5000/dotcv/message-validator-webapp
  tag: testing
  hostname: 192.168.64.35
  port:
    http: 32703
    https: 32704
tim_db:
  image: localhost:5000/dotcv/tim-db
  tag: testing
  storage_class_name: hostpath
  db_name: cvdb
  collection_name: travelerInformation
  port:
    mongodb: 27017
whtools:
  image: localhost:5000/dotcv/whtools-webapp
  tag: testing
  system_name: "SDW 2.3"
  hostname: 192.168.64.35
  port:
    http: 32705
    https: 32706
ssl:
  jetty_keystore_secret:
    name: cas
    key: jetty-keystore
  jetty_keystore_password_secret:
    name: cas
    key: jetty-keystore-password
  trust_keystore: true